name: Build
on: pull_request
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  GITHUB_FEED: https://nuget.pkg.github.com/BusHero/index.json
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # - name: install dependencies
      #   run: .\src\Install-Dependencies.ps1
      - name: setup project
        run: .\src\setup.ps1
      # - name: run tests
      #   run: .\run-tests.ps1
      - name: publish module
        run: .\publish-github.ps1 -ApiKey $GITHUB_TOKEN
