name: continous
on: [pull_request, workflow_dispatch]
jobs:
  Generate-nuget-package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"
      - name: Cache everything
        id: cache-nuke-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            .nuke/temp
            ~/Documents/PowerShell/Modules
          key: ${{ runner.os }}-everything
      - name: Publish to Github
        env:
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: false
        run: ./build.ps1 --verbosity Verbose --target Step1 --NugetApiKey ${{ secrets.POM }}
      - uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: ./test-results
