name: continous

on: [push, workflow_dispatch]

jobs:
  GitVersion:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: Run './build.cmd Print'
        run: dotnet run --project build
